[font]
size = 10

builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
